version: '3'
services:
  api-docker:
    restart: always
    build:
      context: .
      dockerfile: Multistage.dockerfile
    environment:
      PING_LISTEN_PORT: 3000
    deploy:
      replicas: 4
    volumes:
      - ./:/app
    networks:
      - front-network
    expose:
      - 3000

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-docker
    networks:
    - front-network

networks:
  front-network:
    driver: bridge